services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: football-data-pipeline-flaresolverr
    environment:
      - LOG_LEVEL=warn
      - TZ=America/Sao_Paulo
    restart: unless-stopped

  extract-data:
    build:
      context: .
      dockerfile: Dockerfile.extractor
    container_name: football-data-pipeline-data-extraction
    shm_size: 2gb
    volumes:
      - ./data:/app/data
    environment:
      - OUTPUT_DIR=/app/data
      - APP_BASE_DIR=/app
      - TZ=America/Sao_Paulo
      - FLARESOLVERR_URL=http://flaresolverr:8191/v1
    depends_on:
      - flaresolverr      
    profiles:
      - extractor

  postgres:
    image: postgres:15.3-alpine
    container_name: football-data-pipeline-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
      build:
        context: .
        dockerfile: Dockerfile.airflow
      environment:
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      command: >
        bash -c "airflow db migrate &&
        airflow users create --username admin --firstname ${ADMIN_NAME} --lastname ${ADMIN_LASTNAME} --role Admin --email ${ADMIN_EMAIL} --password ${ADMIN_PASSWORD}"
      depends_on:
        - postgres

  airflow-webservice:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: football-data-pipeline-airflow
    depends_on:
      - postgres
      - flaresolverr
    user: root
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: football-data-pipeline-airflow-scheduler
    depends_on:
      - postgres
      - flaresolverr
    user: root
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - TZ=America/Sao_Paulo
    command: scheduler

volumes:
  postgres_data: